const songSort = require('../../api/SortSongData');

describe("truncateTrackData()", () => {
    it("should return truncated data", () => {

        expect(songSort.truncateTrackData({data: 1})).data.toBeTruthy();
    });
});

{
    "album_type": "album",
    "artists": [
    {
        "external_urls": {
            "spotify": "https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW"
        },
        "href": "https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW",
        "id": "55fhWPvDiMpLnE4ZzNXZyW",
        "name": "Noah Cyrus",
        "type": "artist",
        "uri": "spotify:artist:55fhWPvDiMpLnE4ZzNXZyW"
    }
],
    "copyrights": [
    {
        "text": "(P) 2020 Records Label, LLC / Columbia",
        "type": "P"
    }
],
    "external_ids": {
    "upc": "886448371564"
},
    "external_urls": {
    "spotify": "https://open.spotify.com/album/5Gn3fFzlWL89j0hGumtXb5"
},
    "genres": [],
    "href": "https://api.spotify.com/v1/albums/5Gn3fFzlWL89j0hGumtXb5",
    "id": "5Gn3fFzlWL89j0hGumtXb5",
    "images": [
    {
        "height": 640,
        "url": "https://i.scdn.co/image/ab67616d0000b2737f66b73bd6e86f4c8d2a7692",
        "width": 640
    },
    {
        "height": 300,
        "url": "https://i.scdn.co/image/ab67616d00001e027f66b73bd6e86f4c8d2a7692",
        "width": 300
    },
    {
        "height": 64,
        "url": "https://i.scdn.co/image/ab67616d000048517f66b73bd6e86f4c8d2a7692",
        "width": 64
    }
],
    "label": "Records/Columbia",
    "name": "THE END OF EVERYTHING",
    "popularity": 78,
    "release_date": "2020-05-15",
    "release_date_precision": "day",
    "total_tracks": 8,
    "tracks": {
    "href": "https://api.spotify.com/v1/albums/5Gn3fFzlWL89j0hGumtXb5/tracks?offset=0&limit=50",
        "items": [
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW"
                    },
                    "href": "https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW",
                    "id": "55fhWPvDiMpLnE4ZzNXZyW",
                    "name": "Noah Cyrus",
                    "type": "artist",
                    "uri": "spotify:artist:55fhWPvDiMpLnE4ZzNXZyW"
                }
            ],
            "disc_number": 1,
            "duration_ms": 185454,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/4bl5qvLNSJng48smi0uVO7"
            },
            "href": "https://api.spotify.com/v1/tracks/4bl5qvLNSJng48smi0uVO7",
            "id": "4bl5qvLNSJng48smi0uVO7",
            "is_local": false,
            "name": "Ghost",
            "preview_url": "https://p.scdn.co/mp3-preview/6ed63dce3287600a5bbbb961360b84b910ced957?cid=a0b2820d204d4c4e8a88b75a9ce09b34",
            "track_number": 1,
            "type": "track",
            "uri": "spotify:track:4bl5qvLNSJng48smi0uVO7"
        },
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW"
                    },
                    "href": "https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW",
                    "id": "55fhWPvDiMpLnE4ZzNXZyW",
                    "name": "Noah Cyrus",
                    "type": "artist",
                    "uri": "spotify:artist:55fhWPvDiMpLnE4ZzNXZyW"
                }
            ],
            "disc_number": 1,
            "duration_ms": 217714,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/3zQikNPCgTVnQLmj5RPn1k"
            },
            "href": "https://api.spotify.com/v1/tracks/3zQikNPCgTVnQLmj5RPn1k",
            "id": "3zQikNPCgTVnQLmj5RPn1k",
            "is_local": false,
            "name": "I Got So High That I Saw Jesus",
            "preview_url": "https://p.scdn.co/mp3-preview/0d7aab9ce796f4081338d9898a863f856248b80a?cid=a0b2820d204d4c4e8a88b75a9ce09b34",
            "track_number": 2,
            "type": "track",
            "uri": "spotify:track:3zQikNPCgTVnQLmj5RPn1k"
        },
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW"
                    },
                    "href": "https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW",
                    "id": "55fhWPvDiMpLnE4ZzNXZyW",
                    "name": "Noah Cyrus",
                    "type": "artist",
                    "uri": "spotify:artist:55fhWPvDiMpLnE4ZzNXZyW"
                }
            ],
            "available_markets": [
                "AD",
                "AE",
                "AL",
                "AR",
                "AT",
                "AU",
                "BA",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "BY",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HR",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "KZ",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MK",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "SA",
                "SE",
                "SG",
                "SI",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "UA",
                "US",
                "UY",
                "VN",
                "XK",
                "ZA"
            ],
            "disc_number": 1,
            "duration_ms": 172941,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/0AXB2KmgSGjB886FJglrgJ"
            },
            "href": "https://api.spotify.com/v1/tracks/0AXB2KmgSGjB886FJglrgJ",
            "id": "0AXB2KmgSGjB886FJglrgJ",
            "is_local": false,
            "name": "Liar",
            "preview_url": "https://p.scdn.co/mp3-preview/cca5457fd3cf5b3390b2001c624ead9a32dad1f5?cid=a0b2820d204d4c4e8a88b75a9ce09b34",
            "track_number": 3,
            "type": "track",
            "uri": "spotify:track:0AXB2KmgSGjB886FJglrgJ"
        },
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW"
                    },
                    "href": "https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW",
                    "id": "55fhWPvDiMpLnE4ZzNXZyW",
                    "name": "Noah Cyrus",
                    "type": "artist",
                    "uri": "spotify:artist:55fhWPvDiMpLnE4ZzNXZyW"
                }
            ],
            "available_markets": [
                "AD",
                "AE",
                "AL",
                "AR",
                "AT",
                "AU",
                "BA",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "BY",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HR",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "KZ",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MK",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "SA",
                "SE",
                "SG",
                "SI",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "UA",
                "US",
                "UY",
                "VN",
                "XK",
                "ZA"
            ],
            "disc_number": 1,
            "duration_ms": 144377,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/6U1iuA5QfzYRPJxvdcxqtf"
            },
            "href": "https://api.spotify.com/v1/tracks/6U1iuA5QfzYRPJxvdcxqtf",
            "id": "6U1iuA5QfzYRPJxvdcxqtf",
            "is_local": false,
            "name": "Lonely",
            "preview_url": "https://p.scdn.co/mp3-preview/7249052f16402787067ca4da7c97d34682703397?cid=a0b2820d204d4c4e8a88b75a9ce09b34",
            "track_number": 4,
            "type": "track",
            "uri": "spotify:track:6U1iuA5QfzYRPJxvdcxqtf"
        },
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW"
                    },
                    "href": "https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW",
                    "id": "55fhWPvDiMpLnE4ZzNXZyW",
                    "name": "Noah Cyrus",
                    "type": "artist",
                    "uri": "spotify:artist:55fhWPvDiMpLnE4ZzNXZyW"
                }
            ],
            "available_markets": [
                "AD",
                "AE",
                "AL",
                "AR",
                "AT",
                "AU",
                "BA",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "BY",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HR",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "KZ",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MK",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "SA",
                "SE",
                "SG",
                "SI",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "UA",
                "US",
                "UY",
                "VN",
                "XK",
                "ZA"
            ],
            "disc_number": 1,
            "duration_ms": 190182,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/2aav0K63pZ1x2mEj0aDGat"
            },
            "href": "https://api.spotify.com/v1/tracks/2aav0K63pZ1x2mEj0aDGat",
            "id": "2aav0K63pZ1x2mEj0aDGat",
            "is_local": false,
            "name": "Young & Sad",
            "preview_url": "https://p.scdn.co/mp3-preview/c6c396538a426dc98832deba51fe8f038288f6de?cid=a0b2820d204d4c4e8a88b75a9ce09b34",
            "track_number": 5,
            "type": "track",
            "uri": "spotify:track:2aav0K63pZ1x2mEj0aDGat"
        },
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW"
                    },
                    "href": "https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW",
                    "id": "55fhWPvDiMpLnE4ZzNXZyW",
                    "name": "Noah Cyrus",
                    "type": "artist",
                    "uri": "spotify:artist:55fhWPvDiMpLnE4ZzNXZyW"
                }
            ],
            "available_markets": [
                "AD",
                "AE",
                "AL",
                "AR",
                "AT",
                "AU",
                "BA",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "BY",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HR",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "KZ",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MK",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "SA",
                "SE",
                "SG",
                "SI",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "UA",
                "US",
                "UY",
                "VN",
                "XK",
                "ZA"
            ],
            "disc_number": 1,
            "duration_ms": 156106,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/6J2LdBN97cDWn0MLxYh9HB"
            },
            "href": "https://api.spotify.com/v1/tracks/6J2LdBN97cDWn0MLxYh9HB",
            "id": "6J2LdBN97cDWn0MLxYh9HB",
            "is_local": false,
            "name": "July",
            "preview_url": "https://p.scdn.co/mp3-preview/ab4354e7df7fcf4ddb61654fe406629f9353c655?cid=a0b2820d204d4c4e8a88b75a9ce09b34",
            "track_number": 6,
            "type": "track",
            "uri": "spotify:track:6J2LdBN97cDWn0MLxYh9HB"
        },
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW"
                    },
                    "href": "https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW",
                    "id": "55fhWPvDiMpLnE4ZzNXZyW",
                    "name": "Noah Cyrus",
                    "type": "artist",
                    "uri": "spotify:artist:55fhWPvDiMpLnE4ZzNXZyW"
                },
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/028lPW2NdWHdSPCkRkcyhd"
                    },
                    "href": "https://api.spotify.com/v1/artists/028lPW2NdWHdSPCkRkcyhd",
                    "id": "028lPW2NdWHdSPCkRkcyhd",
                    "name": "Ant Clemons",
                    "type": "artist",
                    "uri": "spotify:artist:028lPW2NdWHdSPCkRkcyhd"
                }
            ],
            "available_markets": [
                "AD",
                "AE",
                "AL",
                "AR",
                "AT",
                "AU",
                "BA",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "BY",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HR",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "KZ",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MK",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "SA",
                "SE",
                "SG",
                "SI",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "UA",
                "US",
                "UY",
                "VN",
                "XK",
                "ZA"
            ],
            "disc_number": 1,
            "duration_ms": 198493,
            "explicit": true,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/2M8JffLDYXcGBAnaYB7bVz"
            },
            "href": "https://api.spotify.com/v1/tracks/2M8JffLDYXcGBAnaYB7bVz",
            "id": "2M8JffLDYXcGBAnaYB7bVz",
            "is_local": false,
            "name": "Wonder Years (feat. Ant Clemons)",
            "preview_url": "https://p.scdn.co/mp3-preview/1aed70485bd131c360fc70b520c1be55f7ee6c2a?cid=a0b2820d204d4c4e8a88b75a9ce09b34",
            "track_number": 7,
            "type": "track",
            "uri": "spotify:track:2M8JffLDYXcGBAnaYB7bVz"
        },
        {
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/55fhWPvDiMpLnE4ZzNXZyW"
                    },
                    "href": "https://api.spotify.com/v1/artists/55fhWPvDiMpLnE4ZzNXZyW",
                    "id": "55fhWPvDiMpLnE4ZzNXZyW",
                    "name": "Noah Cyrus",
                    "type": "artist",
                    "uri": "spotify:artist:55fhWPvDiMpLnE4ZzNXZyW"
                }
            ],
            "available_markets": [
                "AD",
                "AE",
                "AL",
                "AR",
                "AT",
                "AU",
                "BA",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "BY",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HR",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "KZ",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MK",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "SA",
                "SE",
                "SG",
                "SI",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "UA",
                "US",
                "UY",
                "VN",
                "XK",
                "ZA"
            ],
            "disc_number": 1,
            "duration_ms": 175683,
            "explicit": false,
            "external_urls": {
                "spotify": "https://open.spotify.com/track/3Svynwi8VIgkDKQQiEPYCB"
            },
            "href": "https://api.spotify.com/v1/tracks/3Svynwi8VIgkDKQQiEPYCB",
            "id": "3Svynwi8VIgkDKQQiEPYCB",
            "is_local": false,
            "name": "The End of Everything",
            "preview_url": "https://p.scdn.co/mp3-preview/0fbca8df677c63232d151f078f210dd7b1dc2d17?cid=a0b2820d204d4c4e8a88b75a9ce09b34",
            "track_number": 8,
            "type": "track",
            "uri": "spotify:track:3Svynwi8VIgkDKQQiEPYCB"
        }
    ],
        "limit": 50,
        "next": null,
        "offset": 0,
        "previous": null,
        "total": 8
},
    "type": "album",
    "uri": "spotify:album:5Gn3fFzlWL89j0hGumtXb5"
}